spring:
  config:
    activate:
      on-profile: prod

  datasource:
    hikari:
      jdbc-url: ${recipe.gpt.spring.datasource.url}
      username: ${recipe.gpt.spring.datasource.username}
      password: ${recipe.gpt.spring.datasource.password}

  security:
    jwt:
      header: ${recipe.gpt.spring.security.jwt.header}
      sign-key: ${recipe.gpt.spring.security.jwt.sign-key}
      access-token-validity-in-seconds: ${recipe.gpt.spring.security.jwt.access-token-validity-in-seconds}
      refresh-token-validity-in-seconds: ${recipe.gpt.spring.security.jwt.refresh-token-validity-in-seconds}
    oauth2:
      client:
        registration:
          google:
            client-id: ${recipe.gpt.spring.oauth.google.client}
            client-secret: ${recipe.gpt.spring.oauth.google.secret}
            redirect-uri: ${recipe.gpt.spring.oauth.google.redirect-uri}
            scope:
              - email
              - profile

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: ${recipe.gpt.spring.data.redis.host}
      port: ${recipe.gpt.spring.data.redis.port}
      database: ${recipe.gpt.spring.data.redis.database}

  servlet:
    multipart:
      max-file-size: 32MB

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"

cloud:
  aws:
    credentials:
      access-key: ${recipe.gpt.aws.credentials.access-key}
      secret-key: ${recipe.gpt.aws.credentials.secret-key}
    s3:
      bucket: ${recipe.gpt.aws.s3.bucket}
    region:
      static:
        ap-northeast-2
    stack:
      auto:
        false

recipe-gpt:
  error:
    redirectUrl: ${recipe-gpt.error.redirectUrl}
  cloudFront:
    distributionDomain: ${recipe.gpt.cloudFront.distributionDomain}

api:
  x-api-key: ${recipe.gpt.api.x-api-key}
  base-url: ${recipe.gpt.api.base-url}
  uri-recommend: ${recipe.gpt.api.uri.recommend}
  uri-recipe: ${recipe.gpt.api.uri.recipe}